name: astroconda
channels:
  - astropy
  - http://ssb.stsci.edu/astroconda
  - defaults
dependencies:
  - astropy-sphinx-theme=1.1=py_0
  - sphinx-astropy=1.1.1=pyhd1c1de3_1
  - sphinx-automodapi=0.11=py_0
  - sphinx-gallery=0.2.0=py35_0
  - alabaster=0.7.11=py35_0
  - appnope=0.1.0=py35hd172556_0
  - asn1crypto=0.24.0=py35_0
  - astropy=3.0.4=py35h1de35cc_0
  - atomicwrites=1.2.0=py35_0
  - attrs=18.1.0=py35_0
  - automat=0.7.0=py35_0
  - babel=2.6.0=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - bleach=2.1.4=py35_0
  - bokeh=0.13.0=py35_0
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35h6174b99_1
  - chardet=3.0.4=py35_1
  - click=6.7=py35hcc65ea6_0
  - cloudpickle=0.5.5=py35_0
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hdbc3d79_0
  - cycler=0.10.0=py35hb89929e_0
  - cython=0.28.5=py35h0a44026_0
  - cytoolz=0.9.0.1=py35h1de35cc_1
  - dask=0.18.2=py35_0
  - dask-core=0.18.2=py35_0
  - dbus=1.13.2=h760590f_1
  - dill=0.2.8.2=py35_0
  - distributed=1.22.1=py35_0
  - docopt=0.6.2=py35_0
  - docutils=0.14=py35hb13dbd9_0
  - entrypoints=0.2.3=py35_2
  - expat=2.2.6=h0a44026_0
  - filelock=3.0.6=py35_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - fribidi=1.0.5=h1de35cc_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - graphite2=1.3.13=h2098e52_0
  - graphviz=2.40.1=hefbbd9a_2
  - h5py=2.8.0=py35h878fce3_3
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - heapdict=1.0.0=py35_2
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h4b95b61_1
  - idna=2.7=py35_0
  - imageio=2.3.0=py35_0
  - imagesize=1.0.0=py35_0
  - incremental=17.5.0=py35_0
  - intel-openmp=2018.0.3=0
  - ipykernel=4.8.2=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hf129286_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py35h2dd9e4b_0
  - jupyter_client=5.2.3=py35_0
  - jupyter_core=4.4.0=py35_0
  - kiwisolver=1.0.1=py35h219a9d8_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgcc=4.8.5=hdbeacc1_10
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.34=he12f830_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=hcb84e12_2
  - libxml2=2.9.8=hab757c2_1
  - libxslt=1.1.32=hb819dd2_0
  - locket=0.2.0=py35h58cf053_1
  - lxml=4.2.4=py35hef8c89e_0
  - markupsafe=1.0=py35h1de35cc_1
  - matplotlib=2.2.3=py35h54f8f79_0
  - mistune=0.8.3=py35h1de35cc_1
  - mkl=2018.0.3=1
  - mkl_fft=1.0.4=py35h5d10147_1
  - mkl_random=1.0.1=py35h5d10147_1
  - more-itertools=4.3.0=py35_0
  - msgpack-python=0.5.6=py35h04f5b5a_1
  - nbconvert=5.3.1=py35_0
  - nbformat=4.4.0=py35h41c2038_0
  - ncurses=6.1=h0a44026_0
  - networkx=2.0=py35hb193ae4_0
  - nose=1.3.7=py35_2
  - notebook=5.6.0=py35_0
  - numpy=1.15.1=py35h6a91979_0
  - numpy-base=1.15.1=py35h8a80b8c_0
  - numpydoc=0.8.0=py35_0
  - olefile=0.45.1=py35_0
  - openssl=1.0.2t=h1de35cc_1
  - packaging=17.1=py35_0
  - pandas=0.23.4=py35h6440ff4_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py35_1
  - pango=1.42.4=h060686c_0
  - parso=0.3.1=py35_0
  - partd=0.3.8=py35h6fadee7_0
  - pathlib2=2.3.2=py35_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35h9517181_0
  - pillow=5.2.0=py35hb68e598_0
  - pip=10.0.1=py35_0
  - pixman=0.38.0=h1de35cc_0
  - pkg-config=0.29.2=h3efe00b_8
  - pkgconfig=1.3.1=py35_0
  - plotly=3.1.1=py35h28b3542_0
  - pluggy=0.7.1=py35h28b3542_0
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35h93950c5_0
  - psutil=5.4.7=py35h1de35cc_0
  - ptyprocess=0.6.0=py35_0
  - py=1.5.4=py35_0
  - pyasn1=0.4.4=py35h28b3542_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.18=py35_1
  - pygments=2.2.0=py35h392a662_0
  - pymysql=0.9.2=py35_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.0=py35_1
  - pyqt=5.9.2=py35h11d3b92_0
  - pysocks=1.6.8=py35_0
  - pytest=3.7.3=py35_0
  - pytest-arraydiff=0.2=py35h39e3cac_0
  - pytest-astropy=0.4.0=py35_0
  - pytest-doctestplus=0.1.3=py35_0
  - pytest-openfiles=0.3.0=py35_0
  - pytest-remotedata=0.3.0=py35_0
  - python=3.5.5=h0a44026_3
  - python-dateutil=2.7.3=py35_0
  - python.app=2=py35_8
  - pytz=2018.5=py35_0
  - pywavelets=0.5.2=py35h9dc8fb8_0
  - pyyaml=3.13=py35h1de35cc_0
  - pyzmq=17.1.2=py35h1de35cc_0
  - qt=5.9.6=h45cd832_2
  - qtconsole=4.4.1=py35_0
  - qtpy=1.5.0=py35_0
  - readline=7.0=h1de35cc_5
  - requests=2.19.1=py35_0
  - retrying=1.3.3=py35_2
  - scikit-image=0.14.0=py35h0a44026_1
  - scikit-learn=0.20.0=py35h4f467ca_1
  - scipy=1.1.0=py35h28f7352_1
  - semantic_version=2.6.0=py35_0
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.12=py35h0a44026_0
  - six=1.11.0=py35_1
  - snowballstemmer=1.2.1=py35hbb7be01_0
  - sortedcontainers=2.0.4=py35_0
  - sphinx=1.7.7=py35_0
  - sphinxcontrib=1.0=py35_1
  - sphinxcontrib-websupport=1.1.0=py35_1
  - sqlite=3.24.0=ha441bb4_0
  - tblib=1.3.2=py35h1b9c5fd_0
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35hf8009f4_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py35_0
  - tornado=5.1=py35h1de35cc_0
  - traitlets=4.3.2=py35hd3d1486_0
  - twisted=17.5.0=py35_0
  - urllib3=1.23=py35_0
  - wcwidth=0.1.7=py35hdd0c235_0
  - webencodings=0.5.1=py35_1
  - wheel=0.31.1=py35_0
  - xlrd=1.1.0=py35_1
  - xz=5.2.4=h1de35cc_4
  - yaml=0.1.7=hc338f04_2
  - zeromq=4.2.5=h0a44026_1
  - zict=0.1.3=py35_0
  - zlib=1.2.11=hf3cbc9b_2
  - zope=1.0=py35_0
  - zope.interface=4.5.0=py35h1de35cc_0
  - acstools=2.0.10=py35_0
  - appdirs=1.4.0=py35_0
  - asdf=2.0.1=py35_1
  - asteval=0.9.11=py35_0
  - astroimtools=0.1.1=py35_2
  - calcos=3.3.4=py35_0
  - cfitsio=3.440=1
  - costools=1.2.2=py35_0
  - crds=7.2.4=py35_1
  - cubeviz=0.0.2=py35_1
  - d2to1=0.2.12=py35_0
  - decorator=4.0.9=py35_0
  - drizzlepac=2.2.4=py35_0
  - ds9=7.5=1
  - fftw=3.3.4=1
  - fitsblender=0.3.2=py35_1
  - fitsverify=4.18=6
  - ginga=2.7.1=py35_0
  - glue-core=0.12.0=py35_0
  - glue-ginga=0.2=py35_0
  - glue-vispy-viewers=0.9=py35_0
  - glueviz=0.12.0=0
  - gwcs=0.9.1=py35_2
  - hstcal=2.0.0=1
  - htc_utils=0.1.0=py35_1
  - imexam=0.8.0=py35_1
  - mosviz=0.1.1=py35_1
  - nictools=1.1.3=py35_2
  - parsley=1.3=py35_1
  - photutils=0.5=py35_0
  - purge_path=1.2.0=py35_0
  - py-expression-eval=0.3.4=py35_1
  - pyds9=1.9.0.dev61+g3761d7a=py35_2
  - pyfftw=0.9.2=py35_3
  - pyopengl=3.1.1a1=py35_0
  - pyqtgraph=0.10.0=py35_0
  - pysynphot=0.9.12=py35_0
  - radio-beam=0.2=py35_0
  - reftools=1.7.4=py35_1
  - spectral-cube=0.4.1=py35_0
  - specutils=0.2.2=py35_2
  - specviz=0.5.0=py35_0
  - spherical-geometry=1.2.4=py35_0
  - stginga=0.3=py35_0
  - stistools=1.1=py35_2
  - stregion=1.1.4=py35_0
  - stsci=3.0.2=py35_1
  - stsci-data-analysis=2.1.1=py35_0
  - stsci-hst=3.0.3=py35_0
  - stsci.convolve=2.2.2=py35_0
  - stsci.distutils=0.3.8=py35_2
  - stsci.image=2.3.0=py35_2
  - stsci.imagemanip=1.1.4=py35_0
  - stsci.imagestats=1.4.2=py35_0
  - stsci.ndimage=0.10.1=py35_2
  - stsci.numdisplay=1.6.1=py35_2
  - stsci.skypac=0.9.15=py35_0
  - stsci.sphere=0.2=py35_2
  - stsci.sphinxext=1.2.2=py35_1
  - stsci.stimage=0.2.2=py35_0
  - stsci.tools=3.4.13=py35_0
  - stwcs=1.4.0=py35_1
  - wfc3tools=1.3.4=py35_2
  - wfpc2tools=1.0.3=py35_2
  - pip:
    - adsbibdesk==3.2.0
    - msgpack==0.5.6
    - popstar==0.0.dev506
    - pyfits==3.5
prefix: /Users/mwhosek/anaconda3/envs/astroconda

